version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myroot
      MONGO_INITDB_ROOT_PASSWORD: somepassword
    volumes:
      - mongo_data:/data/db
    networks:
      - imdb-scraper-network
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myroot
      ME_CONFIG_MONGODB_ADMINPASSWORD: somepassword
    networks:
      - imdb-scraper-network 
    depends_on:
      - mongo

  scraper-api:
    build: ./IMDBScraper.API
    restart: always
    ports:
      - 5000:80
    depends_on:
      - mongo
    networks:
      - imdb-scraper-network

networks:
  imdb-scraper-network:
    driver: bridge
volumes:
  mongo_data:
    driver: local